# Generated by Django 4.0 on 2022-03-14 22:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountDetailsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acct_no', models.IntegerField(blank=True, null=True, unique=True)),
                ('balance', models.FloatField(blank=True, default=0, null=True)),
            ],
            options={
                'db_table': 'account details',
            },
        ),
        migrations.CreateModel(
            name='AccountModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acct_type', models.CharField(max_length=4)),
            ],
            options={
                'db_table': 'account type',
            },
        ),
        migrations.CreateModel(
            name='TransactionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=20, null=True)),
                ('amount', models.FloatField()),
                ('status', models.CharField(blank=True, max_length=10, null=True)),
                ('from_acct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_acct', to='project.accountdetailsmodel')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
                ('to_acct', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='to_acct', to='project.accountdetailsmodel')),
            ],
            options={
                'db_table': 'transfers',
            },
        ),
        migrations.AddField(
            model_name='accountdetailsmodel',
            name='acct_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='project.accountmodel'),
        ),
        migrations.AddField(
            model_name='accountdetailsmodel',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
        ),
    ]
